ansible_user: abhishek
ansible_ssh_pass: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  62383635653237343966623839333230383735646430363562646561353939356161653637343836
  62383635653237343966623839333230383735646430363562646561353939356161653637343836
  32353039346334663337326163626636626438343330643339333434376637643764303665613533
  32353039346334663337326163626636626438343330643339333434376637643764303665613533
  62633336363436356134626663323931323030393965633964393235333663623737

ansible_ssh_private_key_file: ~/keys/ec2-user.pem
